### ISSUE TITLE
482 use

### ISSUE THREAD

**Issue by aortner** [NLS-SJTU/um482_ros_wrapper#1]
sorry for opene an issue.

i did buy a ub482 board.  i am on the start with it..
do you have experiences with the 482?

is it possible to compare it to other dual antenna boards like trimble mb2 or bd982?
of against ublox zed f9p? (single or dual setup) 

best regards from Austria

andreas

**Comment by gauxonz** [comment]
@LugiaLiu @milkytipo

**Comment by LugiaLiu** [comment]
Hi, Andreas

Sorry for the late reply.

UB482 supports dual antennas and can directly output PVT and heading. So you can compare it with other dual antenna boards like trimble mb2 or bd982.

Zed F9P supports L1 and L2 dual frequencies, but it does not support dual antennas. So you can compare their PVT results. 

Best regards.

Qiang
